apiVersion: v1
kind: Service
metadata:
  name: backend

spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80

# selector from the pod definition in the deployments
  selector:
    app: nginx
    tier: backend

