# Not available on minikube, but is on cloud vendors AKS GCP etc

apiVersion: v1
kind: Service
metadata:
  name: nginx-service

spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008

# selector from the pod definition in the deployments
  selector:
    app: nginx
    tier: frontend

